name: Jump Prince build

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build game
        run: |
          chmod u+x ./build.sh
          ./build.sh
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build
        shell: cmd
        # cl.exe isn't available as-is in Github images because they don't want
        # to, so we need to pull env vars ourselves. Refs:
        # https://github.com/actions/runner-images/issues/6205#issuecomment-1241573412
        # https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#create-your-own-command-prompt-shortcut
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat" x64
          call build.bat
